# Generated by Django 4.1.3 on 2022-11-16 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djams', '0004_genre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='title',
            new_name='name',
        ),
    ]
