# Generated by Django 4.1.3 on 2022-11-16 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djams', '0005_rename_title_album_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='title',
            new_name='name',
        ),
    ]
