# Generated by Django 4.1.3 on 2022-11-16 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djams', '0006_rename_title_song_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='djams.genre'),
        ),
    ]
