# Generated by Django 4.1.3 on 2022-11-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djams', '0007_song_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='artist',
            field=models.ManyToManyField(to='djams.artist'),
        ),
    ]
