# Generated by Django 4.1.3 on 2022-11-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djams', '0009_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='playlist',
            field=models.ManyToManyField(to='djams.playlist'),
        ),
    ]
