# Generated by Django 4.1.3 on 2022-11-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djams', '0010_song_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.ManyToManyField(to='djams.album'),
        ),
    ]
