# Generated by Django 4.1.3 on 2022-11-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djams', '0011_song_album'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='playlist',
        ),
    ]
