# Generated by Django 4.1.3 on 2022-11-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djams', '0012_remove_song_playlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ManyToManyField(to='djams.artist'),
        ),
    ]
